// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// convolution_body
arma::mat convolution_body(arma::mat dataset, int threshold, arma::vec integers);
RcppExport SEXP _SPACancer_convolution_body(SEXP datasetSEXP, SEXP thresholdSEXP, SEXP integersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< int >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type integers(integersSEXP);
    rcpp_result_gen = Rcpp::wrap(convolution_body(dataset, threshold, integers));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SPACancer_convolution_body", (DL_FUNC) &_SPACancer_convolution_body, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SPACancer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
