# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convolution_body <- function(dataset, threshold, integers) {
    .Call('_SPACancer_convolution_body', PACKAGE = 'SPACancer', dataset, threshold, integers)
}

